# Generated by Django 5.2.8 on 2025-11-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('available_copies', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
