# Generated by Django 5.2.8 on 2025-11-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_book_is_available_book_available_copies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
    ]
